feat: 마이페이지 상세 UI 레이아웃 구현
kagong-sillok/kagong-sillok-client pull request #23
Opened 2023-06-03 12:25 UTC by YunjiNam

## 💡 이슈
close #3

## 🧑‍💻 작업 사항

- [x]  GNB 구현
- [x]  헤더 UI 구현
- [x]  탭 메뉴 UI 구현
- [x]  리스트 아이템 UI 구현

## 📖 참고 사항
상단 GNB 의 close 버튼은 잠시 disabled 해 놓았습니다~ 추후 이벤트 추가 예정입니다

<img width="200" alt="스크린샷 2023-06-03 오후 9 21 17" src="https://github.com/kagong-sillok/kagong-sillok-client/assets/59434504/380b70ac-b2d7-456b-996b-e40d428341af">
<img width="200" alt="스크린샷 2023-06-03 오후 9 21 29" src="https://github.com/kagong-sillok/kagong-sillok-client/assets/59434504/20eb8133-88f6-42aa-9c4f-6ebf77a5fc59">
<img width="200" alt="스크린샷 2023-06-03 오후 9 21 41" src="https://github.com/kagong-sillok/kagong-sillok-client/assets/59434504/a0792714-5a87-4574-beda-5cd319db9cb8">

2023-06-03 13:19 UTC, kangju2000 commented on src/app/mypage/place/bookmarks/page.tsx
> +import { PlaceShortData } from '@/types/place';
앞에 type 붙여줘!
```suggestion
import type { PlaceShortData } from '@/types/place';
```

2023-06-03 13:19 UTC, kangju2000 commented on src/app/mypage/layout.tsx
> +import { PageType, UserData, ViewType } from '@/types/mypage';
```suggestion
import type { PageType, UserData, ViewType } from '@/types/mypage';
```

2023-06-03 13:44 UTC, kangju2000 commented on src/app/mypage/place/bookmarks/page.tsx
> +    </>
BookmarkItem에서 패딩주지 않고 여기서 패딩주는건 어때? 이러면 라인이 안삐져나올 수 있을 것 같아!
<img width="462" alt="image" src="https://github.com/kagong-sillok/kagong-sillok-client/assets/23312485/4e292a8a-fcc0-45a3-b3ce-dc24c1193cb2">

그리고 key 값으로 item.id가 들어가는게 더 좋을 것 같아!
[[React] 배열의 index를 key로 쓰면 안되는 이유](https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb)

2023-06-03 13:49 UTC, kangju2000 commented on src/components/mypage/BookmarkItem.tsx
> +      <div className="flex w-full items-center justify-between gap-4 p-6">
[여기](https://github.com/kagong-sillok/kagong-sillok-client/pull/23/files#r1215539380)서 말한 것처럼 하면 p-6 지워주면 될거 같아

2023-06-03 13:52 UTC, kangju2000 commented on src/components/mypage/Dot.tsx
이거 내가 `globals.css`에 circle이라는 클래스 만들어뒀는데 여기선 잘 적용이 안되네.. 나중에 circle 클래스 리팩토링해서 적용할 수 있게 되면 이 컴포넌트 대신 사용해도 좋을 것 같아

2023-06-03 13:53 UTC, kangju2000 commented on src/components/mypage/Header.tsx
> +import { PageType, UserData } from '@/types/mypage';
```suggestion
import type { PageType, UserData } from '@/types/mypage';
```

2023-06-03 14:00 UTC, kangju2000 commented on src/types/mypage.tsx
> +export type ViewType = 'bookmarks' | 'reviews' | 'timeline' | 'map';
리터럴 타입들을 대문자로 통일하는거 어떄?

백엔드에서 리터럴 타입들을 대문자로 받아오고 있어서 통일해두는 것도 좋을 것 같은데 어떻게 생각해?
<img width="707" alt="image" src="https://github.com/kagong-sillok/kagong-sillok-client/assets/23312485/f0b13799-34b2-42a3-a27a-d4ab7ec79854">

2023-06-03 14:00 UTC, kangju2000 commented on src/constants/place.ts
> +export const RATING_TEXT = ['별로예요', '그저 그래요', '괜찮아요', '괜찮아요', '최고예요'];
👍👍
```suggestion
export const RATING_TEXT = ['별로예요', '그저 그래요', '괜찮아요', '만족해요', '최고예요'];
```

2023-06-03 14:02 UTC, kangju2000 commented on src/components/mypage/TabGroup.tsx
> +export default function TabGroup({ children }: { children: ReactNode }) {
children만 prop으로 받으면 이렇게 하는 방법도 있어!
```suggestion
import type { PropsWithChildren } from 'react';

export default function TabGroup({ children }: PropsWithChildren) {
```

2023-06-03 14:02 UTC, kangju2000 commented on src/components/mypage/ReviewItem.tsx
> +import Dot from './Dot';
여기 alias로 맞춰줘!

2023-06-03 14:04 UTC, kangju2000 commented on src/components/mypage/ReviewItem.tsx
> +export default function ReviewItem({ data, isLast }: { data: ReviewItem; isLast: boolean }) {
component나 page들의 props는 interface로 빼두는게 일관성 있어 보이는데 어떻게 생각해?

2023-06-03 14:10 UTC, kangju2000 commented on src/app/mypage/place/reviews/page.tsx
> +const reviewList: ReviewData = {
리뷰 더미데이터 내가 `reviews.json`으로 만들어둔거 있는데 올라간 내 pr 머지되면 이거 대신 사용하면 될 것 같아!

2023-06-04 01:57 UTC, kangju2000 commented on src/components/mypage/ReviewItem.tsx
> +  const date = format(new Date(createdAt), 'yyyy.MM.dd');
디자인 상으로는 `yy.MM.dd` 형식이라 이렇게 바꾸면 될 것 같아!
```suggestion
  const date = format(new Date(createdAt), 'yy.MM.dd');
```

2023-06-04 02:48 UTC, YunjiNam commented
@kangju2000 리뷰 수정했어! 확인 부탁해용

2023-06-04 03:30 UTC, kangju2000 commented on src/components/mypage/Header.tsx
> +import { PageType, UserData } from '@/types/mypage';
@YunjiNam 여기도 바꿔줘!

2023-06-04 03:38 UTC, kangju2000 commented on src/constants/place.ts
> +export const RATING_TEXT = ['별로예요', '그저 그래요', '괜찮아요', '괜찮아요', '최고예요'];
@YunjiNam 여기도 수정!

2023-06-04 03:39 UTC, kangju2000 commented on src/components/mypage/Header.tsx
> +          <span className="text-violet/default">{time}</span>째 기록중
디자인에 맞게 카공 뒤에 공백 들어가게 해주면 좋을 것 같아 :)

2023-06-04 03:42 UTC, kangju2000 requested changes
열려있는 코멘트만 수정해주면 굿!!

2023-06-05 08:41 UTC, YunjiNam commented on src/app/mypage/place/bookmarks/page.tsx
> +    </>
오키오키 수정했어~

2023-06-05 08:42 UTC, YunjiNam commented on src/components/mypage/Header.tsx
> +          <span className="text-violet/default">{time}</span>째 기록중
오키오키 수정했어~

2023-06-05 08:48 UTC, kangju2000 commented on src/app/mypage/place/reviews/page.tsx
> +}
key값으로 고유한 값 들어갈 수 있을것 같아!

2023-06-05 08:48 UTC, kangju2000 commented on src/app/mypage/record/timeline/page.tsx
> +}
여기도 key값으로 고유한 값 들어갈 수 있을것 같아!

2023-06-05 08:48 UTC, kangju2000 commented on src/components/mypage/BookmarkItem.tsx
> +            })}
여기도 key값으로 고유한 값 들어갈 수 있을것 같아!

2023-06-05 08:54 UTC, YunjiNam commented on src/app/mypage/place/reviews/page.tsx
> +}
[refactor: key 값 id 사용하도록 변경](https://github.com/kagong-sillok/kagong-sillok-client/pull/23/commits/c9a57fa6b03148e6cb438f2de1c9de395f103106) 수정했어~

2023-06-05 08:55 UTC, YunjiNam commented on src/app/mypage/record/timeline/page.tsx
> +}
[refactor: key 값 id 사용하도록 변경](https://github.com/kagong-sillok/kagong-sillok-client/pull/23/commits/c9a57fa6b03148e6cb438f2de1c9de395f103106) 수정했어~

2023-06-05 08:57 UTC, YunjiNam commented on src/components/mypage/BookmarkItem.tsx
> +            })}
[refactor: key 값 idx 제거](https://github.com/kagong-sillok/kagong-sillok-client/pull/23/commits/455cf6a1a3479638aa524566727ce27ba40cbdc4) 수정했어~

2023-06-05 09:04 UTC, kangju2000 approved these changes
LGTM👍

고생 많았어!!

2023-06-06 04:20 UTC, merged